language: java
install: skip

os: linux

jdk:
  - openjdk-ea
  - openjdk14
  - openjdk11
  - openjdk8

matrix:
  allow_failures:
    - jdk: openjdk-ea

script:
  - ./gradlew clean buildPlugin

deploy:
  provider: releases
  user: "GITHUB USERNAME"
  password: "GITHUB PASSWORD"
  file: build/libs/GsonFormat.jar
  skip_cleanup: true
  on:
    tags: true