language: java
install: skip
os: linux
jdk:
  - openjdk11
  - openjdk8
script:
  - "./gradlew clean buildPlugin"
deploy:
  provider: releases
  api_key:
    secure: QGLspU1Yt8LKMSv9eYF0Hnpvh+9OZPnvjsejo/X3gO5uzsgy/yzjjPThhEWFfCtp1rjRRqJUIUjyR64c5iODB4Hn4RroHj1htoo0gDUYITx3PKGjL19plXYhFXWFgWNWw+w7sjblLPhBOahKqLrDMtbu8jeo8l2nWWVZBsesGM/YiomWYmN5TTjSv3+If6B/Pma0P1v7zQ8fzz4XZl7tyNB5UxOcJCk6MoBCaiC3L/v9EmAwe7TD6jehwbhudhURxucyWh7z3ZNlfX7HtmPtB6btyQjw/MCVPFB5/nT8qKJn8kXw5mjLBKBQ+JnpmAcjrlTFLT0sLOfN6UQez5VE27iZfy8FiY1dWRZS9bDZ56rlicBjLdry/tl7ZIe4ZPVz4zggUjLciJsqOKdwU/1wVoxxSQuNIDiXfahusD8miNLtSfgtPShAL9B9/jVDUMns2WQSn3KZp11u5Sd2sLAD+ufHsRg1ebiE86faxLc9u2WYkZumg/6mahzMuL8nLQB32e0C+5uNV2rsERTWBwcz8EW0f5serjYFxOfJidKSJEqsQpgAQgrh320EGFz87RIqDR86zsU73n47qRIf41fhT+iwI/DtYNH+3rwGol0M8RNNx7vHnhh7HR57TgyWHvVOMDcj9OJtW+dOM8TB41aw/oP59GiWmKD0Zi1p9PnMl18=
  file: 'build/libs/GsonFormat.jar'
  skip_cleanup: 'true'
  on:
    #repo: syusuke/GsonFormat
    tags: true
