language: java
install: skip

os: linux

jdk:
  - openjdk11
  - openjdk8

script:
  - ./gradlew clean buildPlugin

deploy:
  provider: releases
  user: "GITHUB USERNAME"
  password: "GITHUB PASSWORD"
  file: build/libs/GsonFormat.jar
  skip_cleanup: true
  on:
    tags: true